### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by DimonYoing** [NhanAZ-Plugins/ProfanityFilter#5]
Error in console crash

**Comment by NhanAZ** [comment]
Hi @DimonYoing 
`You are using the development builds. Development builds might have unexpected bugs, crash, break your plugins, corrupt all your data and more. Unless you're a developer and know what you're doing, please AVOID using development builds in production!`
By the way can you give me more information about this error?
(Crashdump file, backtrace or something related)
Thank you!

**Comment by Goalkov** [comment]
Error of your class

**Comment by Goalkov** [comment]
writes EXCEPTION

**Comment by NhanAZ** [comment]
This issue will be fixed in the official version!

**Comment by NhanAZ** [comment]
The plugin is still developing at a snail's pace so I will close this issue. Thank you for reporting the bug.
